### ISSUE TITLE
Can't select last  "}" if it is a line end

### ISSUE THREAD

**Issue by obenjiro** [leny/atom-easy-motion-redux#11]
1) try to select last "}"
2) fail

```
import Observer from './../helpers/observer.js'

export default class MainController extends Observer {
    init() {

    }
    onFirstLoad() {
        this.fire('update');
    }
    onItemClick(id) {
        this.fire('item selected', id);
    }
}
```

PS:  works fine if you add some empty lines at the end of the file

**Comment by leny** [comment]
The bug is larger than that: the last lines are ignored (regardless the letter submitted) to prevent having markers over the input, because the panels system on Atom place the new panels _over_ the text editors.  
I'll try to find a way to fix this, but I suspect that it needs more than just a bunch of minutes, which I can't allow on this plugin right now.

Feel free to investigate by yourself if you want.

**Comment by wabilin** [comment]
#30 Fixed this issue 🎉
